### PR TITLE
Change names of tutorials that are for algorithms to start with algor…

### PR DESCRIPTION
**Pull request by jeremy-myers**
…ithm_

----
:books: Documentation preview :books:: https://pyttb--273.org.readthedocs.build/en/273/

### CODE REVIEW

**Comment by jeremy-myers** [comment]
`ttensor_reconstruct.ipynb` isn't a class or an algorithm -- is there any naming convention we want to follow for tutorials of this nature?

**Comment by dmdunla** [comment]
@jeremy-myers Can this be folded into the `class_ttensor` tutorial? It seems like it belongs there to me instead of some new, separate tutorial.

**Comment by jeremy-myers** [comment]
That's a good idea. I'll open an issue and merge it into this PR?

**Comment by dmdunla** [comment]
Just make the change here. No need for a separate PR, as this arose when addressing this issue -- there was no clear name for that tutorial content.

**Review by dmdunla — APPROVED** [review]
@jeremy-myers Can you add an Issue about using `matplotlib` plots in tutorials and how that breaks the CI regressions? THere is currently a TODO in the notebook, but this would be better captured as an Issue for later use. I suggest it be an enhancement rather than a blocker for 2.0.

**Pull request merged**
