### PR TITLE
Nick/pyttb utils improvement

### PR DESCRIPTION
**Pull request by ntjohnson1**
Solves #347
Also handles the [tenfun discussion]](https://github.com/sandialabs/pyttb/discussions/345#discussioncomment-11442298)
Additonally, enables ruff's enforcement of pydocstyle which should help the uniformity of our documentation. There are always documentation style improvements but I realized there were some methods we were just entirely missing docs one. (This is a single commit but if it is annoying to review can put it into a separate PR)

Resolves: #357 and #355 (the naming in the printing of the tensor will depend on #350)

----
📚 Documentation preview 📚: https://pyttb--353.org.readthedocs.build/en/353/

### CODE REVIEW

**Comment by dmdunla** [comment]
@ntjohnson1 Looks like the same conflicts (and maybe a couple more) are still in place for this PR. Since I broke the last conflict fix, I'll ask you to fix the conflicts when you get a chance. Thanks

**Comment by ntjohnson1** [comment]
I'll try to get to it tonight or tomorrow.

**Comment by ntjohnson1** [comment]
No problem Danny I usually telescope my PRs to stack them for review but didn't this time and conflicts were a pain. I'll go back to stacking them and describe the right order of merging for the future.

**Review by dmdunla — APPROVED** [review]
Fixed all of the conflicts!

**Pull request merged**
