### PR TITLE
Hosvd

### PR DESCRIPTION
**Pull request by ntjohnson1**
Addressing https://github.com/sandialabs/pyttb/issues/56

I left some todos in the code/maybe are bigger topics around how we control verbosity and printing vs logging etc throughout the code base. There is the ongoing discussion around our incremental typing support so I added the final commit to enable some typing support of hosvd. There will be more discussion/work around how we test for scalar values.

### CODE REVIEW

**Review by dmdunla — APPROVED** [review]
Still some work to do, but approving and merging this version as is.

**Comment by dmdunla** [comment]
Since we moved to Update -> PR -> Approval -> Merge by author workflow, @ntjohnson1 please merge now that approval is complete.

**Comment by ntjohnson1** [comment]
> Still some work to do, but approving and merging this version as is.

Did you have specific things that looked like they were missing (if so can you create an issue with them listed?) . As far as an initial port/translation I believe this to be complete. My notes in the description were mostly around making things more pythonic/further cleanup across the repo in general. With the request to merge sooner this could probably use a little more testing/validation, but conceptually I don't think there was anything missing I am aware of.

**Comment by dmdunla** [comment]
I must have been looking at an older version. This looks great!
________________________________
From: Nick ***@***.***>
Sent: Thursday, March 16, 2023 7:00:41 AM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Daniel M ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] Hosvd (PR #67)


Still some work to do, but approving and merging this version as is.

Did you have specific things that looked like they were missing (if so can you create an issue with them listed?) . As far as an initial port/translation I believe this to be complete. My notes in the description were mostly around making things more pythonic/further cleanup across the repo in general. With the request to merge sooner this could probably use a little more testing/validation, but conceptually I don't think there was anything missing I am aware of.

**Pull request merged**
