### PR TITLE
153 how should this be cited

### LINKED ISSUE #153: How should this be cited?
How should this be cited?

### PR DESCRIPTION
**Pull request by dmdunla**
This will add a new feature to get the APA or BibTeX citation for pyttb.

You will be able to click on "Cite this repository" on the "About" panel.

Closes #153.

----
:books: Documentation preview :books:: https://pyttb--268.org.readthedocs.build/en/268/

### CODE REVIEW

**Comment by dmdunla** [comment]
BTW, the BibTeX entry appears like this:

```
@misc{Dunlavy_pyttb_Python_Tensor_2023,
	author = {Dunlavy, Daniel M. and Johnson, Nicholas T. and Myers, Jeremy M. and Medina, Jordan S.},
	month = jun,
	title = {{pyttb: Python Tensor Toolbox, v1.6.2}},
	url = {https://github.com/sandialab/pyttb},
	year = {2023}
}
```

which renders with `siamplain` bibliographystype, for example, as

D. M. Dunlavy, N. T. Johnson, J. M. Myers, and J. S. Medina, _pyttb: Python Tensor Toolbox, v1.6.2_, June 2023, [https://github.com/sandialab/pyttb](https://github.com/sandialab/pyttb).

**Comment by ntjohnson1** [comment]
Hmm, It [looks like](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#other-citation-files) github magic works for a few other file formats. Thoughts on using a generic .bib file? I am not sure if anyone needs anything besides the LaTex. The benefit is that we can then link it to our read the docs as well/link to the source from our README. Ideally, we reduce the number of places you have to update things when we do a new release.

**Comment by dmdunla** [comment]
I looked in that as you’ll see from my commits. It adds a link but does not parse the file unless it is .cff format. So I opted for that. The link takes you to a file page and renders the .bib text. The .cff file parses and renders APA and .bib text with a help copy button. I thought that would allow for a better flow. If you want to see that, let me know and I’ll show you. 

I may be missing your point of using a bib file, too.

**Comment by dmdunla** [comment]
I think I see how the .bib would be more useful now for other docs.

**Review by ntjohnson1 — APPROVED** [review]
Looks good to me. Small comment is that it would be nice to add a link to the bib from the landing page on RTD and our README.

**Comment by dmdunla** [comment]
Will add placement of the citation to the getting started Issue:

- #110

**Pull request merged**
